import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../l10n/app_strings.dart';
import '../models/patient_info.dart';
import '../models/scan_result.dart';
import '../providers/app_provider.dart';
import '../services/tts_service.dart';
import '../theme/app_theme.dart';
import 'scan_screen.dart';

class SymptomsScreen extends StatefulWidget {
  final Uint8List                  imageBytes;
  final ScanType                   scanType;
  final List<Map<String, dynamic>> questions;
  final PatientInfo                patientInfo;
  final List<String>               selectedSymptoms;
  final List<String>               riskFactors;
  final String                     duration;

  const SymptomsScreen({
    super.key,
    required this.imageBytes,
    required this.scanType,
    required this.questions,
    required this.patientInfo,
    this.selectedSymptoms = const [],
    this.riskFactors = const [],
    this.duration = '',
  });

  @override
  State<SymptomsScreen> createState() => _SymptomsScreenState();
}

class _SymptomsScreenState extends State<SymptomsScreen> {
  final Map<String, String> _answers = {};

  void _proceed() {
    final type = widget.scanType == ScanType.oral ? 'oral' : 'skin';
    Navigator.pushReplacement(
      context,
      MaterialPageRoute(
        builder: (_) => ScanScreen(
          imageBytes:   widget.imageBytes,
          scanType:     widget.scanType,
          symptoms:     Map.from(_answers),
          scanTypeName: type,
          patientInfo:  widget.patientInfo,
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final lang = context.watch<AppProvider>().langCode;
    final s    = AppStrings(lang);

    return Scaffold(
      backgroundColor: context.primaryBg,
      appBar: AppBar(title: Text(s.scanTitle)),
      body: Column(
        children: [
          // Progress indicator showing Gemini source
          Container(
            width: double.infinity,
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
            color: context.accent.withValues(alpha: 0.08),
            child: Row(children: [
              Icon(Icons.auto_awesome, color: context.accent, size: 16),
              const SizedBox(width: 8),
              Text(
                lang == 'hi'
                    ? 'AI ने आपकी तस्वीर देखकर ये प्रश्न बनाए'
                    : 'Questions generated by AI from your photo',
                style: TextStyle(
                    color: context.accent, fontSize: 12,
                    fontWeight: FontWeight.w500),
              ),
            ]),
          ),
          Expanded(
            child: widget.questions.isEmpty
                ? Center(
                    child: ElevatedButton(
                      onPressed: _proceed,
                      child: Text(s.scanAnalyze),
                    ),
                  )
                : SingleChildScrollView(
                    padding: const EdgeInsets.all(16),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        ...widget.questions.map((q) => _QuestionCard(
                          question: q,
                          lang:     lang,
                          selected: _answers[q['en']?.toString() ?? q['id']?.toString() ?? ''],
                          onSelected: (enAnswer) {
                            final key = q['en']?.toString() ?? q['id']?.toString() ?? '';
                            setState(() => _answers[key] = enAnswer);
                          },
                        )),
                        const SizedBox(height: 24),
                        ElevatedButton(
                          onPressed: _proceed,
                          child: Text(s.scanAnalyze),
                        ),
                        const SizedBox(height: 8),
                        SizedBox(
                          width: double.infinity,
                          child: TextButton(
                            onPressed: _proceed,
                            child: Text(
                              lang == 'hi'
                                  ? 'प्रश्न छोड़ें और सीधे जांच करें'
                                  : 'Skip questions and proceed',
                              style: TextStyle(color: context.textSec),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
          ),
        ],
      ),
    );
  }
}

class _QuestionCard extends StatefulWidget {
  final Map<String, dynamic> question;
  final String  lang;
  final String? selected;
  final void Function(String) onSelected;

  const _QuestionCard({
    required this.question,
    required this.lang,
    required this.selected,
    required this.onSelected,
  });

  @override
  State<_QuestionCard> createState() => _QuestionCardState();
}

class _QuestionCardState extends State<_QuestionCard> {
  bool _speaking = false;

  String get _qText {
    return widget.question[widget.lang] as String?
        ?? widget.question['en'] as String?
        ?? '';
  }

  List<String> get _options {
    final key = 'options_${widget.lang}';
    final raw = (widget.question[key] as List?)
        ?? (widget.question['options_en'] as List?)
        ?? [];
    return raw.map((e) => e.toString()).toList();
  }

  List<String> get _optionsEn {
    final raw = (widget.question['options_en'] as List?) ?? [];
    return raw.map((e) => e.toString()).toList();
  }

  // Returns the English equivalent of a localized option
  String _toEnglish(String localizedOpt) {
    final idx = _options.indexOf(localizedOpt);
    final en  = _optionsEn;
    return (idx >= 0 && idx < en.length) ? en[idx] : localizedOpt;
  }

  Future<void> _speakQuestion() async {
    if (_speaking) {
      await TtsService().stop();
      setState(() => _speaking = false);
    } else {
      setState(() => _speaking = true);
      TtsService().onStop = () {
        if (mounted) setState(() => _speaking = false);
      };
      await TtsService().speak(_qText, langCode: widget.lang);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.only(bottom: 14),
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: context.cardBg,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: context.border),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Question text + TTS button
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Expanded(
                child: Text(_qText,
                    style: TextStyle(
                        color: context.textPrimary,
                        fontSize: 14, fontWeight: FontWeight.w500,
                        height: 1.4)),
              ),
              // TTS button for this question
              IconButton(
                icon: Icon(
                  _speaking ? Icons.stop_circle_outlined : Icons.volume_up_outlined,
                  color: context.accent, size: 20,
                ),
                onPressed: _speakQuestion,
                tooltip: _speaking
                    ? AppStrings(widget.lang).ttsStop
                    : AppStrings(widget.lang).ttsListen,
                padding: const EdgeInsets.only(left: 8),
                constraints: const BoxConstraints(),
              ),
            ],
          ),
          const SizedBox(height: 10),
          // Options
          Wrap(
            spacing: 8,
            runSpacing: 8,
            children: _options.map((opt) {
              final active = widget.selected == _toEnglish(opt);
              return GestureDetector(
                onTap: () => widget.onSelected(_toEnglish(opt)),
                child: AnimatedContainer(
                  duration: const Duration(milliseconds: 150),
                  padding: const EdgeInsets.symmetric(
                      horizontal: 14, vertical: 8),
                  decoration: BoxDecoration(
                    color: active
                        ? context.accent
                        : context.secondaryBg,
                    borderRadius: BorderRadius.circular(20),
                    border: Border.all(
                        color: active ? context.accent : context.border),
                  ),
                  child: Text(opt,
                      style: TextStyle(
                          color: active ? Colors.white : context.textPrimary,
                          fontSize: 13, fontWeight: FontWeight.w500)),
                ),
              );
            }).toList(),
          ),
        ],
      ),
    );
  }
}
